import React from "react";

export default function Team() {
  return (
    <div>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
      <p>Team</p>
    </div>
  );
}
